services:
  - type: web
    name: conectaking-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Otimizações de build
    buildFilter:
      paths:
        - /**
      ignoredPaths:
        - node_modules/**
        - .git/**
        - *.md
        - public/**
        - views/**
        - migrations/**
        - scripts/**
        - .cursor/**
