<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        // Atrás do Caddy/Node (proxy /l)
        $middleware->trustProxies(at: '*');
        // sendBeacon do cartão público (sem CSRF token)
        $middleware->validateCsrfTokens(except: [
            'log/*',
            'api/profile',
            'api/profile/*',
            'api/upload',
            'api/upload/*',
            '*/form/*/submit',
            'api/bible/prosperidade/mark-read',
            'api/bible/devotional/mark-read',
            'api/bible/mark-read',
            'api/bible/reset-progress',
            'api/guest-lists/public/register/*',
            'api/guest-lists/public/confirm/*',
            'portaria/*/checkin/*',
            'guest-list/view-full/*/checkin/*',
            'guest-list/confirm/qr/*',
            'guest-list/confirm/cpf',
            'api/guest-lists',
            'api/guest-lists/*',
            'api/guest-lists/*/customize-portaria',
            'api/guest-lists/*/customize-confirmacao',
            'api/guest-lists/*/customize-inscricao',
            'api/admin/bible/prosperidade',
            'api/admin/bible/prosperidade/*',
            'api/admin/bible/devotionals-365',
            'api/admin/bible/devotionals-365/*',
            'api/admin/bible/study',
            'api/admin/bible/study/*',
            'api/king-selection/client/login',
            'api/king-selection/client/login-by-details',
            'api/king-selection/client/register',
            'api/king-selection/client/public-enter',
            'api/king-selection/client/signup-enter',
            'api/king-selection/client/select',
            'api/king-selection/client/select-bulk',
            'api/king-selection/client/finalize',
            'api/king-selection/client/edit-request',
            'api/king-selection/client/edit-request/*/cancel',
            'api/auth/login',
            'api/auth/refresh',
            'api/auth/logout',
            'api/business/branding',
            'api/finance/king-data',
            'api/finance/transactions',
            'api/finance/transactions/*',
            'api/finance/cards',
            'api/finance/cards/*',
            'api/finance/categories',
            'api/finance/accounts',
            'api/finance/goals',
            'api/finance/goals/*',
            'api/finance/profiles',
            'api/finance/profiles/*',
            'api/finance/upgrade-plans',
            'api/finance/whatsapp-config',
            'api/finance/zerar-senha-status',
            'api/finance/zerar-senha',
            'api/finance/zerar-senha/*',
            'api/finance/zerar-mes',
            'api/finance/admin/clientes-senhas',
            'api/finance/budgets',
            'api/finance/reports/*',
            'api/finance/transfer',
            'api/finance/upload',
            'api/finance/serasa/*',
            'api/king-selection/galleries',
            'api/king-selection/galleries/*',
            'api/king-selection/galleries/*/status',
            'api/king-selection/galleries/*/photos',
            'api/king-selection/galleries/*/photos/batch',
            'api/king-selection/galleries/*/photos/worker-commit',
            'api/king-selection/galleries/*/uploads/proxy',
            'api/king-selection/galleries/*/uploads/presign-batch',
            'api/king-selection/galleries/*/folders',
            'api/king-selection/galleries/*/folders/generate',
            'api/king-selection/galleries/*/folders/reorder',
            'api/king-selection/galleries/*/photos/assign-folder',
            'api/king-selection/galleries/*/watermark',
            'api/king-selection/galleries/*/thank-you-image',
            'api/king-selection/galleries/*/open-selection-round',
            'api/king-selection/galleries/*/ai/share-text',
            'api/king-selection/galleries/*/ai/sales-whatsapp-template',
            'api/king-selection/galleries/*/ai/support-default-message',
            'api/king-selection/galleries/*/edit-requests',
            'api/king-selection/galleries/*/edit-requests/*',
            'api/king-selection/galleries/*/clients/*/delete-selection-batch',
            'api/king-selection/galleries/*/clients/*/reactivate-selection-batch',
            'api/king-selection/galleries/*/clients/*/clear-review',
            'api/king-selection/galleries/*/photos/delete-batch',
            'api/king-selection/galleries/*/clients',
            'api/king-selection/galleries/*/clients/*',
            'api/king-selection/galleries/*/sales-config',
            'api/king-selection/galleries/*/sales/clients',
            'api/king-selection/galleries/*/sales/clients/*/round/*',
            'api/king-selection/galleries/*/sales/clients/*/round/*/payment-terms',
            'api/king-selection/galleries/*/sales/clients/*/round/*/payment-review',
            'api/king-selection/galleries/*/sales/clients/*/round/*/approve-photo',
            'api/king-selection/galleries/*/sales/clients/*/round/*/approve-all',
            'api/king-selection/galleries/*/uploads/worker-token',
            'api/king-selection/galleries/*/reset-password',
            'api/king-selection/galleries/*/clients/*/enroll-face',
            'api/king-selection/galleries/*/link-cover-upload',
            'api/king-selection/galleries/*/photos/*/edited-upload',
            'api/king-selection/photos/*',
            'api/king-selection/photos/*/replace-r2',
            'api/king-selection/photos/*/replace',
            'api/king-selection/photos/*/replace-proxy',
            'api/king-selection/galleries/*/folders/*',
            'api/king-selection/galleries/*/folders/auto-separate-by-face',
            'api/king-selection/galleries/*/folders/auto-separate-job/*/cancel',
            'api/king-selection/galleries/*/folders/auto-separate-job/start',
            'api/king-selection/galleries/*/photos/*/process-faces',
            'api/king-selection/galleries/*/process-all-faces',
            'api/king-selection/facial/process',
            'api/king-selection/facial/clients/*/faces',
            'api/king-selection/client/payment-proof',
            'api/king-selection/client/promo-verify',
            'api/king-selection/client/enroll-face-image',
            'api/king-selection/client/face-enroll-cache',
            'api/king-selection/client/reset-face-session',
            'api/king-selection/client/search-face-by-photo',
            'api/king-selection/public/enroll-face-anonymous',
            'api/king-selection/client/download-zip-plan',
            'api/king-selection/client/download-zip',
            'api/account/status',
            'api/account/details',
            'api/account/password',
            'api/account/upgrade',
            'api/auth/register',
            'api/subscription/plans/*',
            'api/link-limits',
            'api/link-limits/*',
            'api/password/forgot',
            'api/password/reset',
            'api/documentos',
            'api/documentos/*',
            'api/king-docs',
            'api/king-docs/*',
            'api/admin/link-preview-config',
            'api/inquiry/submit',
            'api/generator/new-key',
            'api/suggestions/generate',
            'api/location/config/*',
            'api/push/subscribe',
            // Stubs 410 (checkout fora de escopo) — sem CSRF para devolver 410 limpo
            'api/payment/create-preference',
            'api/payment/webhook-notification',
            'api/checkout',
            'api/checkout/*',
            'api/orcamentos',
            'api/orcamentos/*',
            'api/business/codes',
            'api/business/generate-code',
            'api/business/codes/generate-manual',
            'api/v1/sales-pages',
            'api/v1/sales-pages/*',
            'api/admin/default-branding',
            'api/admin/plans/*',
            // Painel ADM (JWT + middleware admin; front legado sem CSRF token)
            'api/admin',
            'api/admin/*',
        ]);
        $middleware->encryptCookies(except: [
            'ks_client_token',
            'token',
        ]);
        $middleware->alias([
            'jwt' => \App\Http\Middleware\AuthenticateJwt::class,
            'admin' => \App\Http\Middleware\AuthenticateAdmin::class,
            'ks.client' => \App\Http\Middleware\AuthenticateKsClient::class,
            'module' => \App\Http\Middleware\RequireModule::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();
